#!/bin/bash
systemctl enable notify_bot_1.service
systemctl enable notify_bot_2.service
systemctl enable notify_bot_3.service
systemctl enable notify_bot_4.service
systemctl enable notify_bot_5.service
systemctl enable notify_bot_6.service
systemctl enable notify_bot_7.service
systemctl enable notify_bot_8.service
systemctl enable notify_bot_9.service
systemctl enable notify_bot_10.service
systemctl start notify_bot_1.service
systemctl start notify_bot_2.service
systemctl start notify_bot_3.service
systemctl start notify_bot_4.service
systemctl start notify_bot_5.service
systemctl start notify_bot_6.service
systemctl start notify_bot_7.service
systemctl start notify_bot_8.service
systemctl start notify_bot_9.service
systemctl start notify_bot_10.service
apachectl -k graceful
