# Generated by Django 3.2.6 on 2022-12-17 23:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleAccount',
            fields=[
                ('login', models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='login')),
                ('password', models.CharField(blank=True, max_length=1000, null=True, verbose_name='password')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Apple ID Account',
                'verbose_name_plural': 'Apple ID Accounts',
            },
        ),
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 17, 23, 51, 5, 663974), null=True, verbose_name='Check date and time')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code')),
                ('balance', models.FloatField(blank=True, max_length=1000000, null=True, verbose_name='Balance')),
                ('is_checked', models.BooleanField(blank=True, default=False, null=True, verbose_name='Checked')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Apple Gift Code',
                'verbose_name_plural': 'Apple Gift Codes',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Parser In (time)')),
                ('primary_color', models.CharField(blank=True, choices=[('primary', 'Pink'), ('blue', 'Blue'), ('orange', 'Orange'), ('red', 'Red'), ('green', 'Green')], default='Pink', max_length=100, verbose_name='Basic App Color')),
                ('main_theme', models.CharField(blank=True, choices=[('white-content', 'Light'), ('', 'Dark')], default='Dark', max_length=100, verbose_name='Theme')),
                ('tz', models.CharField(blank=True, choices=[('+4 Москва', 'Москва'), ('+4 СПб', 'СПб'), ('+6 Екатеринбург', 'Екатеринбург')], default='Москва', max_length=100, verbose_name='City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings',
            },
        ),
    ]
