# Generated by Django 3.2.6 on 2022-12-17 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_giftcode_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcode',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 17, 23, 54, 23, 298112), null=True, verbose_name='Check date and time'),
        ),
    ]
