# Generated by Django 3.2.6 on 2022-12-23 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_giftcode_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleaccount',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='appleaccount',
            name='report',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='report'),
        ),
        migrations.AddField(
            model_name='giftcode',
            name='report',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='appleaccount',
            name='login',
            field=models.CharField(max_length=1000, null=True, unique=True, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='appleaccount',
            name='password',
            field=models.CharField(max_length=1000, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 23, 15, 55, 28, 679758), null=True, verbose_name='Check date and time'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='tz',
            field=models.CharField(blank=True, choices=[('-12 International Date Line West', '-12 UTC International Date Line West'), ('-11 Coordinated Universal Time-11', '-11 UTC Coordinated Universal Time-11'), ('-10 Hawaii', '-10 UTC Hawaii'), ('-09 Alaska', '-09 UTC Alaska'), ('-08 Pacific Time (US & Canada)', '-08 UTC Pacific Time (US & Canada)'), ('-07 Mountain Time (US & Canada)', '-07 UTC Mountain Time (US & Canada)'), ('-06 Central Time (US & Canada)', '-06 UTC Central Time (US & Canada)'), ('-05 Eastern Time (US & Canada)', '-05 UTC Eastern Time (US & Canada)'), ('-04 Georgetown, La Paz, Manaus, San Juan', '-04  UTC Georgetown, La Paz, Manaus, San Juan'), ('-03 Buenos Aires', '-03 UTC Buenos Aires'), ('-02 Coordinated Universal Time-02', '-02 UTC Coordinated Universal Time-02'), ('-01 Cape Verde Is.', '-01 UTC Cape Verde Is.'), ('+00 Dublin, Edinburgh, Lisbon, London', '+00 UTC Dublin, Edinburgh, Lisbon, London'), ('+01 Brussels, Copenhagen, Madrid, Paris', '+01 UTC Brussels, Copenhagen, Madrid, Paris'), ('+02 E. Europe', '+02 UTC E. Europe'), ('+03 Baghdad', '+03 UTC Baghdad'), ('+04 Moscow', '+04 UTC Moscow'), ('+04 SPB', '+04 UTC SPB'), ('+05 Ashgabat, Tashkent', '+05 UTC Ashgabat, Tashkent'), ('+06 Yekaterinburg', '+06 UTC Yekaterinburg'), ('+07 Novosibirsk', '+07 UTC Novosibirsk'), ('+08 Krasnoyarsk', '+08 UTC Krasnoyarsk'), ('+09 Irkutsk', '+09 UTC Irkutsk'), ('+10 Canberra, Melbourne, Sydney', '+10 UTC Canberra, Melbourne, Sydney'), ('+11 Vladivostok', '+11 UTC Vladivostok'), ('+12 Magadan', '+12 UTC Magadan'), ('+13 Samoa', '+13 UTC Samoa')], default='Москва', max_length=100, verbose_name='Time Zone'),
        ),
    ]
