# Generated by Django 3.2.6 on 2022-12-23 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221223_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcode',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 23, 16, 2, 41, 878367), null=True, verbose_name='Check date and time'),
        ),
    ]
