# Generated by Django 3.2.6 on 2023-01-05 11:17

import apps.home.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_giftcode_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUpload',
            fields=[
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsm', 'xlsx'])], verbose_name='File')),
                ('is_checked', models.BooleanField(blank=True, default=False, null=True, verbose_name='Uploaded')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Account File',
                'verbose_name_plural': 'Account Files',
            },
        ),
        migrations.CreateModel(
            name='CodeUpload',
            fields=[
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsm', 'xlsx'])], verbose_name='File')),
                ('is_checked', models.BooleanField(blank=True, default=False, null=True, verbose_name='Uploaded')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Code File',
                'verbose_name_plural': 'Code Files',
            },
        ),
        migrations.AddField(
            model_name='giftcode',
            name='init_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 5, 11, 17, 14, 994959), null=True, verbose_name='Date registry'),
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[apps.home.validators.check_code], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='giftcode',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check date and time'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='start_time',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Start Parser In (time)'),
        ),
    ]
