# Generated by Django 4.2 on 2023-05-01 07:50

import apps.home.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20230105_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('ref', models.CharField(max_length=100, validators=[apps.home.validators.validate_bot_ref_https], verbose_name='Ссылка на бота')),
                ('token', models.CharField(max_length=300, verbose_name='Бот Токен')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Назавание бота')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало работы Бота')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('reference', models.CharField(max_length=200, null=True, unique=True, validators=[apps.home.validators.validate_contains_https], verbose_name='Ссылка на чат')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название канала')),
                ('image', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на изображение канала')),
                ('chat_id', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='ID чата')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('day', models.CharField(choices=[('1', 'День 1'), ('2', 'День 2'), ('3', 'День 3'), ('4', 'День 4'), ('5', 'День 5'), ('6', 'День 6'), ('7', 'День 7'), ('8', 'День 8'), ('9', 'День 9'), ('10', 'День 10'), ('11', 'День 11'), ('12', 'День 12'), ('13', 'День 13'), ('14', 'День 14'), ('15', 'День 15'), ('16', 'День 16'), ('17', 'День 17'), ('18', 'День 18'), ('19', 'День 19'), ('20', 'День 20'), ('21', 'День 21'), ('22', 'День 22'), ('23', 'День 23'), ('24', 'День 24'), ('25', 'День 25'), ('26', 'День 26'), ('27', 'День 27'), ('28', 'День 28'), ('29', 'День 29'), ('30', 'День 30'), ('31', 'День 31')], max_length=100, verbose_name='День по порядку публикации')),
                ('text', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Текст')),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отправлено')),
                ('media_file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'mp3', 'mp4', 'mpeg', 'avi'])], verbose_name='Медиа файл')),
                ('post_time', models.TimeField(blank=True, null=True, verbose_name='Время публикации')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='AccountUpload',
        ),
        migrations.DeleteModel(
            name='AppleAccount',
        ),
        migrations.DeleteModel(
            name='CodeUpload',
        ),
        migrations.DeleteModel(
            name='GiftCode',
        ),
    ]
