# Generated by Django 4.2 on 2023-05-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bot_chat_post_delete_accountupload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='main_theme',
            field=models.CharField(blank=True, choices=[('white-content', 'Светлый'), ('', 'Тёмный')], default='Тёмный', max_length=100, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='primary_color',
            field=models.CharField(blank=True, choices=[('primary', 'Розовый'), ('blue', 'Синий'), ('orange', 'Оранжевый'), ('red', 'Красный'), ('green', 'Зеленый')], default='Розовый', max_length=100, verbose_name='Основной цвет приложения'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='tz',
            field=models.CharField(blank=True, choices=[('-12 International Date Line West', '-12 UTC International Date Line West'), ('-11 Coordinated Universal Time-11', '-11 UTC Coordinated Universal Time-11'), ('-10 Hawaii', '-10 UTC Hawaii'), ('-09 Alaska', '-09 UTC Alaska'), ('-08 Pacific Time (US & Canada)', '-08 UTC Pacific Time (US & Canada)'), ('-07 Mountain Time (US & Canada)', '-07 UTC Mountain Time (US & Canada)'), ('-06 Central Time (US & Canada)', '-06 UTC Central Time (US & Canada)'), ('-05 Eastern Time (US & Canada)', '-05 UTC Eastern Time (US & Canada)'), ('-04 Georgetown, La Paz, Manaus, San Juan', '-04  UTC Georgetown, La Paz, Manaus, San Juan'), ('-03 Buenos Aires', '-03 UTC Buenos Aires'), ('-02 Coordinated Universal Time-02', '-02 UTC Coordinated Universal Time-02'), ('-01 Cape Verde Is.', '-01 UTC Cape Verde Is.'), ('+00 Dublin, Edinburgh, Lisbon, London', '+00 UTC Dublin, Edinburgh, Lisbon, London'), ('+01 Brussels, Copenhagen, Madrid, Paris', '+01 UTC Brussels, Copenhagen, Madrid, Paris'), ('+02 E. Europe', '+02 UTC E. Europe'), ('+03 Baghdad', '+03 UTC Baghdad'), ('+04 Moscow', '+04 UTC Moscow'), ('+04 SPB', '+04 UTC SPB'), ('+05 Ashgabat, Tashkent', '+05 UTC Ashgabat, Tashkent'), ('+06 Yekaterinburg', '+06 UTC Yekaterinburg'), ('+07 Novosibirsk', '+07 UTC Novosibirsk'), ('+08 Krasnoyarsk', '+08 UTC Krasnoyarsk'), ('+09 Irkutsk', '+09 UTC Irkutsk'), ('+10 Canberra, Melbourne, Sydney', '+10 UTC Canberra, Melbourne, Sydney'), ('+11 Vladivostok', '+11 UTC Vladivostok'), ('+12 Magadan', '+12 UTC Magadan'), ('+13 Samoa', '+13 UTC Samoa')], default='+06 Yekaterinburg', max_length=100, verbose_name='Time Zone'),
        ),
    ]
