# Generated by Django 4.2 on 2023-05-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_usersettings_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
    ]
