# Generated by Django 3.2.18 on 2023-05-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_post_day_alter_post_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-day'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
