# Generated by Django 4.2 on 2023-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_post_options_bot_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-day'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='bot',
            name='is_started',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Старт бота'),
        ),
    ]
