# Generated by Django 3.2.18 on 2023-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_started',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Старт бота'),
        ),
    ]
