# Generated by Django 4.2 on 2023-05-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_post_options_bot_is_started'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
