# Generated by Django 4.2.4 on 2023-10-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_chat_day_alter_post_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Изображение чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название чата'),
        ),
    ]
