# Generated by Django 4.2.4 on 2023-10-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_chat_image_alter_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
