# Generated by Django 4.2.4 on 2023-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_chat_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='', verbose_name='Изображение чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='image_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
