# Generated by Django 4.2.4 on 2023-10-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_chat_image_alter_chat_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Пост', 'Пост'), ('Опрос', 'Опрос')], default='Пост', max_length=50, verbose_name='Тип сообщения'),
        ),
    ]
