# Generated by Django 4.2.4 on 2023-10-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_post_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
    ]
