# Generated by Django 4.2.4 on 2023-11-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_post_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('day', models.IntegerField(choices=[(1, 'День 1'), (2, 'День 2'), (3, 'День 3'), (4, 'День 4'), (5, 'День 5'), (6, 'День 6'), (7, 'День 7'), (8, 'День 8'), (9, 'День 9'), (10, 'День 10'), (11, 'День 11'), (12, 'День 12'), (13, 'День 13'), (14, 'День 14'), (15, 'День 15'), (16, 'День 16'), (17, 'День 17'), (18, 'День 18'), (19, 'День 19'), (20, 'День 20'), (21, 'День 21'), (22, 'День 22'), (23, 'День 23'), (24, 'День 24'), (25, 'День 25'), (26, 'День 26'), (27, 'День 27'), (28, 'День 28'), (29, 'День 29'), (30, 'День 30'), (31, 'День 31')], max_length=100, verbose_name='День по порядку публикации')),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отправлено')),
                ('post_time', models.TimeField(blank=True, null=True, verbose_name='Время публикации')),
                ('question', models.TextField(max_length=1000, verbose_name='Текст')),
                ('option_1', models.TextField(max_length=500, verbose_name='Вариант 1')),
                ('option_2', models.TextField(blank=True, max_length=500, null=True, verbose_name='Вариант 2')),
                ('option_3', models.TextField(blank=True, max_length=500, null=True, verbose_name='Вариант 3')),
                ('option_4', models.TextField(blank=True, max_length=500, null=True, verbose_name='Вариант 4')),
                ('option_5', models.TextField(blank=True, max_length=500, null=True, verbose_name='Вариант 5')),
                ('option_6', models.TextField(blank=True, max_length=500, null=True, verbose_name='Вариант 6')),
                ('option_7', models.TextField(blank=True, max_length=500, null=True, verbose_name='Вариант 7')),
                ('option_8', models.TextField(blank=True, max_length=500, null=True, verbose_name='Вариант 8')),
                ('option_9', models.TextField(blank=True, max_length=500, null=True, verbose_name='Вариант 9')),
                ('option_10', models.TextField(blank=True, max_length=500, null=True, verbose_name='Вариант 10')),
                ('is_anonymous', models.BooleanField(blank=True, default=True, null=True, verbose_name='Анонимный опрос')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
