# Generated by Django 4.2.4 on 2023-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToMail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Пользователь для рассылки',
                'verbose_name_plural': 'Пользователи для рассылки',
            },
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(max_length=1000, verbose_name='Вопрос'),
        ),
    ]
